Adding Tree View Standalone Selection Type
masastack/BlazorComponent pull request #508
Opened 2023-11-14 13:19 UTC by wisamidris7

This Is For Supporting A Different Selection Type

2023-11-14 13:23 UTC, wisamidris7 commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +            if (SelectionType == SelectionType.Standalone)
This To Support The Standalone For Permissions Tree

2023-11-14 13:24 UTC, wisamidris7 commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +                if (SelectionType == SelectionType.Independent || SelectionType == SelectionType.Standalone)
Here I Want To Make Standalone Same Independent But It Effect His Children But His Children Can't Effect Him

2023-11-14 13:24 UTC, wisamidris7 commented on src/Component/BlazorComponent/Components/Treeview/SelectionType.cs
> +        Independent,
I Added Enum Type

2023-11-15 03:02 UTC, capdiem commented
@wisamidris7 Hey, let me guess your usage scenario: after selecting a child node, its ancestor nodes will be selected, just like in `SelectionType=SelectionType.Leaf`. However, the selected items returned by `SelectionType.Leaf` will not include ancestor nodes, and you want to include ancestor nodes, right?

![image](https://github.com/masastack/BlazorComponent/assets/16507773/d6e5cfc9-9bce-4005-a854-1255676d9f75)

2023-11-15 03:05 UTC, capdiem commented
@wisamidris7 If so, I don't recommend adding a new SelectionType. Maybe add a new property of boolean type, which can return the ancestor node of the selected item when turned on.

2023-11-15 18:38 UTC, wisamidris7 commented
This Is Anathor Type Cause It's Like Leaf But If I Off All Children Children Won't Effect Their Parent But Parent Can Effect All He's Children

And Parent No Need To Have The Third The Minus Icon_

2023-11-15 18:41 UTC, wisamidris7 commented
But When I See That It's Not Gonna Be A Boolean Cause Selection Type Is Better

2023-11-15 18:42 UTC, wisamidris7 commented
Or Do It By Your Self But What I Care About Is The Same Result

2023-11-15 19:46 UTC, wisamidris7 commented
For Example Like This

https://github.com/masastack/MASA.Blazor/assets/104096256/890621cf-7948-4a0f-8fb2-d40a50cf9abc

2023-11-16 12:26 UTC, capdiem commented
I see.

2023-11-18 16:45 UTC, wisamidris7 commented
> I see.

I don't understand what gonna happen

2023-11-21 03:06 UTC, capdiem requested changes
in `UpdateParentSelected()`:

```diff
- if (isIndeterminate)
+ if (SelectionType == SelectionType.LeafButIndependentParent)
+ {
+   nodeState.IsSelected = true;
+   nodeState.IsIndeterminate = false;
+ }
+ else if (isIndeterminate)
```

2023-11-21 03:06 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +                if (SelectionType == SelectionType.Independent || SelectionType == SelectionType.Standalone)
I think `LeafButIndependentParent` is better than `Standalone`.

```suggestion
                if (SelectionType is SelectionType.Independent or SelectionType.LeafButIndependentParent)
```

2023-11-21 03:06 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +                if (SelectionType != SelectionType.Independent && SelectionType != SelectionType.Standalone && parent != null && !Nodes.ContainsKey(key) &&
```suggestion
                if (SelectionType == SelectionType.Leaf && parent != null && !Nodes.ContainsKey(key) &&
```

2023-11-21 03:06 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +                if (newNode.IsSelected && ((SelectionType == SelectionType.Independent || SelectionType == SelectionType.Standalone) || !newNode.Children.Any()))
```suggestion
                if (newNode.IsSelected && (SelectionType != SelectionType.Leaf || !newNode.Children.Any()))
```

2023-11-21 03:06 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/SelectionType.cs
> +        Independent,
`LeafButIndependentParent` is better

2023-11-21 03:09 UTC, capdiem commented
@wisamidris7 I basically agree with your functional request, but there are some questions, I have commented, please check!

2023-11-24 01:24 UTC, capdiem requested changes
There is still some code that has not changed, please make sure the build passes and verify that it is the feature you want.

[feature/treeview-leaf-but-indep-parent](https://github.com/masastack/BlazorComponent/compare/main...feature/treeview-leaf-but-indep-parent) This is the branch where I implemented this feature, and if you don't want to make further changes, you can close this PR.

2023-11-26 21:56 UTC, closed without merging