feat: support source generation in System.Text.Json
masastack/BlazorComponent pull request #545
Opened 2024-01-23 09:05 UTC by pigwing

help aot
see:  https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-6-0

2024-01-23 16:04 UTC, capdiem requested changes

2024-01-23 16:04 UTC, capdiem commented on src/Component/BlazorComponent/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
> +        }
不需要添加这样的扩展方法吧，组件库内部直接注册此options就好了？

2024-01-24 01:28 UTC, pigwing commented on src/Component/BlazorComponent/JSInterop/LocalStorage.cs
> -        var json = JsonSerializer.Serialize(value);
@capdiem 主要是LocalStorage这里,有个泛型,若外部用到非基本类型序列化的话,就需要知道TValue的对象meta结构了.

2024-01-24 01:42 UTC, capdiem commented on src/Component/BlazorComponent/JSInterop/LocalStorage.cs
> -        var json = JsonSerializer.Serialize(value);
你给泛型方法加个 JsonSerializerOptions 入参，不用依赖注入。

2024-01-24 01:45 UTC, pigwing commented on src/Component/BlazorComponent/JSInterop/LocalStorage.cs
> -        var json = JsonSerializer.Serialize(value);
就是options模式?

2024-01-24 01:51 UTC, pigwing commented on src/Component/BlazorComponent/JSInterop/LocalStorage.cs
> -        var json = JsonSerializer.Serialize(value);
![image](https://github.com/masastack/BlazorComponent/assets/8393545/c1298ee8-45f1-42bd-974f-6842aae32dd3)
![image](https://github.com/masastack/BlazorComponent/assets/8393545/8f0dd181-f5e7-4a75-9aef-973504f775c2)
但这default只是个get,无法外部全局设置

2024-01-24 02:52 UTC, capdiem commented on src/Component/BlazorComponent/JSInterop/LocalStorage.cs
> -        var json = JsonSerializer.Serialize(value);
```cs
public async Task SetItemAsync<TValue>(string key, TValue value, JsonSerializerOptions options)
{
   ...
}
```

这样，用户自己的类自己去写 *JsonContext 的代码。

2024-02-29 14:34 UTC, capdiem requested changes

2024-02-29 14:34 UTC, capdiem commented on src/Component/BlazorComponent/Components/MobilePicker/BMobilePickerView.razor.cs
> +
```suggestion

```

2024-02-29 14:34 UTC, capdiem commented on src/Component/BlazorComponent/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
> +using BlazorComponent.Components.OtpInput;
```suggestion
using BlazorComponent;
```

2024-02-29 14:48 UTC, capdiem approved these changes
Thanks!

2024-02-29 14:49 UTC, merged