fix(treeview):multiple modifications and optimizations
masastack/BlazorComponent pull request #555
Opened 2024-01-31 07:05 UTC by wildwind2000

1.Fix change parameter from program not correct affect node state.(Value,Open,Active,Openall) 
2.Change parameter from program(Open,Active,Value) should not trigger event. 
3.Optimize search execution efficiency.

2024-01-31 09:12 UTC, capdiem requested changes

2024-01-31 09:12 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +                ComputedItems = Items.Where(r => !ExcludedKeys.Contains(ItemKey.Invoke(r))).ToList();
```c#
if (_preSearch != Search)
{
  _prevSearch = Search;

  // logic
}
```

2024-02-01 02:36 UTC, wildwind2000 commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +namespace BlazorComponent
ok

2024-02-01 02:36 UTC, wildwind2000 commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +namespace BlazorComponent
ok

2024-02-01 02:36 UTC, wildwind2000 commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +                ComputedItems = Items.Where(r => !ExcludedKeys.Contains(ItemKey.Invoke(r))).ToList();
ok

2024-02-01 07:17 UTC, capdiem requested changes

2024-02-01 07:17 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +        List<TItem>? ComputedItems;
Please use underscored lower camel case naming, move to line 10.

2024-02-01 07:17 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +
```suggestion

```

2024-02-01 07:17 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +        ///
```suggestion
        /// Update the selection state of node.
```

2024-02-01 07:17 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +                    store.Add(nodeState);
```suggestion

                // value not contain parent when selection type is Leaf
                if (SelectionType != SelectionType.Leaf)
                {
                    store.Add(nodeState);
                }
```

2024-02-01 07:17 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +        }
```suggestion
        }

```

2024-02-01 07:17 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +            ExploreForKeys(list,li,1);
```suggestion
            ExploreForKeys(list, li, 1);
```

2024-02-01 07:17 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +                if (children is not null && children.Count>0)
```suggestion
                if (children is not null && children.Count > 0)
```

2024-02-01 07:17 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +        public Dictionary<TKey, NodeState<TItem, TKey>> Nodes { get; private set; } = [];
```suggestion

        public Dictionary<TKey, NodeState<TItem, TKey>> Nodes { get; private set; } = [];
```

2024-02-01 07:41 UTC, capdiem requested changes

2024-02-01 07:41 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +            return !string.IsNullOrEmpty(Search) && _excludedKeys?.Contains(key) == true;
```suggestion
            return !string.IsNullOrEmpty(Search) && _excludedKeys?.Contains(key) is true;
```

2024-02-01 07:41 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +                                   .Where(r => nodeState.Children?.Contains(r.Key) == true)
```suggestion
                                   .Where(r => nodeState.Children?.Contains(r.Key) is true)
```

2024-02-01 07:41 UTC, capdiem commented on src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
> +        List<TItem>? _computedItems;
```suggestion
        private HashSet<TKey>? _excludedKeys;
        private List<TItem>? _computedItems;
```

2024-02-01 09:10 UTC, capdiem approved these changes
Thank you so much for your PR! Your work is greatly appreciated!

2024-02-01 09:10 UTC, merged