修正bform动态表单,rest与validate不一致的问题.
masastack/BlazorComponent pull request #602
Opened 2024-04-12 02:12 UTC by pigwing

因reset需要重置表单内容,无法使用foreach进行遍历.修正表单内,动态增减input,Validatable发生不一致的异常

2024-04-12 03:59 UTC, capdiem requested changes

2024-04-12 03:59 UTC, capdiem commented on src/Component/BlazorComponent/Components/Form/BForm.razor.cs
>              }
validatables修改了， for 就不会报错了？

2024-04-12 03:59 UTC, capdiem commented on src/Component/BlazorComponent/Components/Form/BForm.razor.cs
> +
这个干嘛用的？

2024-04-12 05:56 UTC, pigwing commented on src/Component/BlazorComponent/Components/Form/BForm.razor.cs
>              }
是的.因为reset会修改对象,然后就报
![cbe8a38244a69a4ae690fb4bd358b9c](https://github.com/masastack/BlazorComponent/assets/8393545/d44d98c2-43ec-4258-a828-527d9d12940e)

2024-04-12 05:58 UTC, pigwing commented on src/Component/BlazorComponent/Components/Form/BForm.razor.cs
> +
当form内部有个变量,控制动态生成N个binput的时候,开始页面有3个input的,然后我修改了条件,此时页面就只有1个input了,这时候input就会触发dispose,需要把这2个input的validate从validatables中移除,不然会报
![71729b247cbbf35636536b05fd263f0](https://github.com/masastack/BlazorComponent/assets/8393545/c56cd9dd-caf5-4f6d-b59f-d2f94073119a)

2024-04-12 05:59 UTC, pigwing commented on src/Component/BlazorComponent/Components/Form/BForm.razor.cs
> -            _ = UpdateValue(true);
但我看你代码是一样的?

2024-04-12 06:12 UTC, pigwing commented on src/Component/BlazorComponent/Components/Form/BForm.razor.cs
> -            _ = UpdateValue(true);
依,我发现我拉取下来的git上的代码,这里不一致,我改回去

2024-04-12 10:18 UTC, capdiem requested changes

2024-04-12 10:18 UTC, capdiem commented on src/Component/BlazorComponent/Components/Form/BForm.razor.cs
> +        public void Remove(IValidatable validatable)
```suggestion
        internal void Remove(IValidatable validatable)
```

2024-04-13 16:45 UTC, capdiem approved these changes
Thanks!

2024-04-13 16:49 UTC, merged